In [64]:
!pip install nltk

Requirement already satisfied: nltk in c:\users\20b01\anaconda3\anac\lib\site-packages (3.7)
Requirement already satisfied: joblib in c:\users\20b01\anaconda3\anac\lib\site-packages (from nltk) (1.1.0)
Requirement already satisfied: tqdm in c:\users\20b01\anaconda3\anac\lib\site-packages (from nltk) (4.64.1)
Requirement already satisfied: click in c:\users\20b01\anaconda3\anac\lib\site-packages (from nltk) (8.0.4)
Requirement already satisfied: regex>=2021.8.3 in c:\users\20b01\anaconda3\anac\lib\site-packages (from nltk) (2022.7.9)
Requirement already satisfied: colorama in c:\users\20b01\anaconda3\anac\lib\site-packages (from click->nltk) (0.4.5)

In [65]:
import numpy as np
import pandas as pd
import ast
import nltk

In [66]:
movies = pd.read_csv('tmdb_5000_movies.csv')
credits = pd.read_csv('tmdb_5000_credits.csv')

In [67]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [68]:
credits.head(1)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [69]:
movies = movies.merge(credits,on='title')

In [70]:
movies.shape

(4809, 23)

In [71]:
credits.shape

(4803, 4)

In [72]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [73]:
movies = movies[['movie_id','title','overview','genres','keywords','cast','crew']]

In [74]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [75]:
movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [76]:
movies.dropna(inplace=True)

In [77]:
movies.duplicated().sum()

0

In [78]:
def convert(obj):
  L=[]
  for i in ast.literal_eval(obj):
    L.append(i['name'])
  return L

In [79]:
movies['genres'] = movies['genres'].apply(convert)

In [80]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [81]:
movies['keywords'] = movies['keywords'].apply(convert)

In [82]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [83]:
def convert3(obj):
  L=[]
  counter=0
  for i in ast.literal_eval(obj):
    if counter != 3:
       L.append(i['name'])
       counter+=1
    else:
      break
  return L

In [84]:
movies['cast'] = movies['cast'].apply(convert)

In [85]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, LÃ©a Seydoux, R...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman, A...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton,...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [86]:
def fetch_director(obj):
  L=[]
  for i in ast.literal_eval(obj):
    if i['job'] == 'Director':
       L.append(i['name'])
       break
  return L

In [87]:
movies['crew'] = movies['crew'].apply(convert)

In [88]:
movies['overview'] = movies['overview'].apply(lambda x:x.split())

In [89]:
movies['genres'] = movies['genres'].apply(lambda x:[i.replace(" ","") for i in x])
movies['keywords'] = movies['keywords'].apply(lambda x:[i.replace(" ","") for i in x])
movies['cast'] = movies['cast'].apply(lambda x:[i.replace(" ","") for i in x])
movies['crew'] = movies['crew'].apply(lambda x:[i.replace(" ","") for i in x])

In [90]:
movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

In [91]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver, ...","[StephenE.Rivkin, RickCarter, ChristopherBoyes...","[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley, Ste...","[DariuszWolski, GoreVerbinski, JerryBruckheime...","[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LÃ©aSeydoux, Ralp...","[ThomasNewman, SamMendes, AnnaPinnock, JohnLog...","[A, cryptic, message, from, Bondâ€™s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman, Anne...","[HansZimmer, CharlesRoven, ChristopherNolan, C...","[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton, Wi...","[AndrewStanton, AndrewStanton, JohnLasseter, C...","[John, Carter, is, a, war-weary,, former, mili..."

In [92]:
new_df = movies[['movie_id','title','tags']]

In [93]:
new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))

C:\Users\20b01\AppData\Local\Temp\ipykernel_15664\3089450492.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))

In [94]:
new_df['tags'][0]

"In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy ScienceFiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d SamWorthington ZoeSaldana SigourneyWeaver StephenLang MichelleRodriguez GiovanniRibisi JoelDavidMoore CCHPounder WesStudi LazAlonso DileepRao MattGerald SeanAnthonyMoran JasonWhyte ScottLawrence KellyKilgour JamesPatrickPitt SeanPatrickMurphy PeterDillon KevinDorman KelsonHenderson DavidVanHorn JacobTomuri MichaelBlain-Rozgay JonCurry LukeHawker WoodySchultz PeterMensah SoniaYee JahnelCurfman IlramChoi KylaWarren LisaRoumain DebraWilson ChrisMala TaylorKibby JodieLandau JulieLamm CullenB.Madden JosephBradyMadden FrankieTorres AustinWilson SaraWilson TamicaWashington-Miller LucyBriant NathanMeister GerryBlair MatthewChamberlain PaulYates WrayWilson JamesGaylyn MelvinLenoClarkIII CarvonFutrell BrandonJelkes MicahMoch HanniyahMuhammad ChristopherNolen ChristaOliver AprilMarieThomas BravitaA.Threatt ColinBleasdale MikeBodnar MattClayton NicoleDionne JamieHarrison AllanHenry AnthonyIngruber AshleyJeffery DeanKnowsley JosephMika-Hunt TerryNotary KaiPantano LoganPithyou StuartPollock Raja GarethRuck RhianSheehan T.J.Storm JodieTaylor AliciaVela-Bailey RichardWhiteside NikieZambo JuleneRenee StephenE.Rivkin RickCarter ChristopherBoyes ChristopherBoyes MaliFinn JamesHorner JamesCameron JamesCameron JamesCameron JamesCameron JamesCameron AndrewMenzies JillBrooks MargerySimkin KevinIshioka DickBernstein ShannonMills DennieThorpe JanaVance DeborahLynnScott JonLandau SeanHaworth KimSinclair KimSinclair RichardF.Mays LaetaKalogridis MayesC.Rubeo MauroFiore ScottHerbertson WoodySchultz LindaDeVetta LindaDeVetta RichardBluck SimonBright RichardMartin SteveR.Moore JohnRefoua KarlJ.Martin ChilingLin IlramChoi StevenQuale CarlaMeyer NickBassett JillCormack AndyMcLaren TerryNotary GarrettWarren JonathanRothbart StefanDechant ToddCherniawsky MirandaRivers RobertStromberg JohnHarding RobertoDeAngelis MikeSmithson AlainLalanne LucasSalton JanaceTashjian StephenRosenbaum FrankieKarena LisaLovaas JonathanFawkner RobertBavin AnthonyAlmaraz CarolynM.Fenton BethKoenigsberg SamPage TexKadonaga KimFoscato TammyS.Lee DennyCaira JamesWaitkus AddisonTeague C.ScottBaker LukeCaska DavidChow JonathanDyer JosephHiura RebeccaJellie RobertAndrewJohnson MikeStassi JohnVillarino JeffreyWisniewski CherylNardi MarshallWinn GwendolynYatesWhittle WilliamStein LulaWashington ChrisDelConte R.ChristopherWhite DanLemmon TimNielsen MichaelMulholland ThomasNittmann EdsonWilliams ChristineCarr JohnBruno DavidEmmerichs ChristopherScarabosio JenniferTeves BrigitteYorke KenFischer IainHutton SteveIngram JoyceCox JennyFoster ChristopherMarino JimMilton CyndiOchs LucasPutnam Anthony'Max'Ivins JohnKnoll EricSaindon WayneStables DavidStinnett GuyWilliams StuartThorp GilesCoburn MarkFellman ScottSprague JeremyHollobon OrlandoMeunier TaisukeTanimura LiliaMishelAcevedo AlejandroM.Hernandez MarvinHall JudyAlley MikePerry AndrewMorley SethEngstrom EricOliver MatsuneSuzuki PaulTobin RoxaneGriffin ArunRam-Mohan GeorgiaLockhart-Adams ThrainShadbolt BradAlexander ShadiAlmassizadeh SimonClutterbuck GraemeDemmocks AdrianFernandes MitchGates JerryKung AndyLomas SebastianMarino MatthiasMenz SergeiNevshupov PhilippeRebours MichaelTakarangi DavidWeitzberg BenWhite MinWindle"

In [95]:
new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

C:\Users\20b01\AppData\Local\Temp\ipykernel_15664\3214958533.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

In [96]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words='english')

In [97]:
vectors = cv.fit_transform(new_df['tags']).toarray()

In [98]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [99]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [100]:
def stem(text):
  y=[]
  for i in text.split():
    y.append(ps.stem(i))
  return " ".join(y)

In [101]:
stem('Why you are seeing the see')

'whi you are see the see'

In [102]:
new_df['tags'] = new_df['tags'].apply(stem)

C:\Users\20b01\AppData\Local\Temp\ipykernel_15664\3213734980.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(stem)

In [103]:
cv.get_feature_names()

C:\Users\20b01\anaconda3\anac\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

['000',
 '10',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '18',
 '1930s',
 '1940s',
 '1950s',
 '1960s',
 '1970s',
 '1980s',
 '19th',
 '19thcentury',
 '20',
 '20th',
 '24',
 '30',
 '3d',
 '40',
 '50',
 'aaroneckhart',
 'aaronseltzer',
 'aaronwilliams',
 'aaronzigman',
 'abandoned',
 'abigailbreslin',
 'ability',
 'able',
 'abrams',
 'abuse',
 'academy',
 'accepts',
 'accident',
 'accidentally',
 'account',
 'accused',
 'ackerman',
 'act',
 'action',
 'actions',
 'activities',
 'actor',
 'actress',
 'actually',
 'adam',
 'adamdale',
 'adamgoldberg',
 'adammckay',
 'adammilosmalley',
 'adams',
 'adamsandler',
 'adamscott',
 'adamshankman',
 'adaptation',
 'addiction',
 'adewaleakinnuoye',
 'adopted',
 'adoption',
 'adrienbrody',
 'adult',
 'adultery',
 'adventure',
 'adventures',
 'advice',
 'affair',
 'afghanistan',
 'africa',
 'african',
 'aftercreditsstinger',
 'afterlife',
 'agbaje',
 'age',
 'aged',
 'agency',
 'agent',
 'agents',
 'aging',
 'ago',
 'agree',
 'agrees',
 'aguilar',
 'ahead',
 'ai',
 'aid',
 'aidanquinn',
 'air',
 'airplane',
 'airport',
 'akivagoldsman',
 'al',
 'alanalda',
 'alanarkin',
 'alancumming',
 'aland',
 'alanmenken',
 'alanrickman',
 'alanrobertmurray',
 'alansilvestri',
 'alantudyk',
 'alaska',
 'albert',
 'albertbrooks',
 'albertgasser',
 'albertr',
 'albertwolsky',
 'alcohol',
 'alcoholic',
 'alcoholism',
 'alecbaldwin',
 'alechammond',
 'alejandrogonzÃ¡leziÃ±Ã¡rritu',
 'alessandro',
 'alex',
 'alexanderpayne',
 'alexandredesplat',
 'alexapenavega',
 'alexgibson',
 'alexkendrick',
 'alexkurtzman',
 'alexrouse',
 'alfonsocuarÃ³n',
 'alfredhitchcock',
 'alfredmolina',
 'alfrewoodard',
 'alice',
 'aliciastevenson',
 'alien',
 'alieninvasion',
 'aliens',
 'alive',
 'allen',
 'allencovert',
 'allenhall',
 'allied',
 'allies',
 'allisonjanney',
 'allisonjones',
 'ally',
 'alpacino',
 'alter',
 'alternate',
 'alysondeemoore',
 'amanda',
 'amandamackey',
 'amandapeet',
 'amandaseyfried',
 'amazing',
 'ambition',
 'ambitious',
 'ambush',
 'america',
 'american',
 'americanfootball',
 'americans',
 'amico',
 'amnesia',
 'amp',
 'amyadams',
 'amypoehler',
 'amysmart',
 'anamariaquintana',
 'anastasn',
 'ancient',
 'anderson',
 'andiemacdowell',
 'andrew',
 'andrewa',
 'andrewadamson',
 'andrewcooper',
 'andrewdecristofaro',
 'andrewdunn',
 'andrewg',
 'andrewlaws',
 'andrewlazar',
 'andrewlesnie',
 'andrewm',
 'andrewmenzies',
 'andrewneskoromny',
 'andrewniccol',
 'andrews',
 'andrewstanton',
 'android',
 'andrzejbartkowiak',
 'andy',
 'andydick',
 'andygarcÃ­a',
 'andykaplan',
 'andymalcolm',
 'andynelson',
 'andyrichter',
 'andysamberg',
 'andyserkis',
 'angel',
 'angelabassett',
 'angeles',
 'angelinajolie',
 'angelo',
 'anger',
 'angerio',
 'angry',
 'animal',
 'animals',
 'animated',
 'animation',
 'anjelicahuston',
 'ann',
 'anna',
 'annab',
 'annabehlmer',
 'annafaris',
 'annakendrick',
 'annapaquin',
 'annapinnock',
 'annarane',
 'anndowd',
 'anne',
 'annefletcher',
 'annehathaway',
 'anneheche',
 'annekuljian',
 'annemccarthy',
 'annemoss',
 'annettebening',
 'annie',
 'anniepenn',
 'anniewelles',
 'annroth',
 'annscibelli',
 'anntenggren',
 'annual',
 'answer',
 'answers',
 'anthony',
 'anthonyanderson',
 'anthonyb',
 'anthonybregman',
 'anthonydininno',
 'anthonyhopkins',
 'anthonyj',
 'anthonykatagas',
 'anthonymackie',
 'anthonyminghella',
 'anthonyrizzo',
 'anti',
 'antihero',
 'antoni',
 'antonicorone',
 'antoniobanderas',
 'antonyelchin',
 'apart',
 'apartment',
 'apocalypse',
 'apocalyptic',
 'apone',
 'appears',
 'apple',
 'apprentice',
 'april',
 'archaeologist',
 'architect',
 'arcy',
 'area',
 'arena',
 'armed',
 'arms',
 'armstrong',
 'army',
 'armyanbernstein',
 'arnold',
 'arnoldschwarzenegger',
 'arnonmilchan',
 'arrest',
 'arrested',
 'arrival',
 'arrive',
 'arrives',
 'art',
 'arthur',
 'arthurj',
 'arthurmax',
 'arthurschmidt',
 'artificialintelligence',
 'artist',
 'artists',
 'artlinson',
 'arts',
 'ashley',
 'ashleyjudd',
 'ashtonkutcher',
 'asked',
 'asks',
 'aspiring',
 'assassin',
 'assassination',
 'assassins',
 'assault',
 'assigned',
 'assignment',
 'assistant',
 'astronaut',
 'asylum',
 'ateah',
 'attack',
 'attacked',
 'attacks',
 'attempt',
 'attempts',
 'attention',
 'attorney',
 'attractive',
 'audition',
 'aunt',
 'austin',
 'australia',
 'australian',
 'author',
 'authorities',
 'auto',
 'avenge',
 'aviarad',
 'avilerner',
 'avoid',
 'avykaufman',
 'award',
 'away',
 'awry',
 'baby',
 'bachelor',
 'backdrop',
 'bad',
 'bailey',
 'baker',
 'balance',
 'ball',
 'ballet',
 'band',
 'bank',
 'banker',
 'bar',
 'barbarabroccoli',
 'barbaraharris',
 'barbrastreisand',
 'barely',
 'barney',
 'barry',
 'barrybernardi',
 'barrychusid',
 'barryh',
 'barrylevinson',
 'barrymendel',
 'barrypepper',
 'barrysonnenfeld',
 'base',
 'baseball',
 'based',
 'basedoncomicbook',
 'basedonnovel',
 'basedonplay',
 'basedontrueevents',
 'basedontruestory',
 'basedontvseries',
 'basedonvideogame',
 'basedonyoungadultnovel',
 'basement',
 'basiliwanyk',
 'basilpoledouris',
 'basketball',
 'batman',
 'battle',
 'battles',
 'battling',
 'bazluhrmann',
 'beach',
 'bear',
 'beast',
 'beat',
 'beatrixarunapasztor',
 'beauborders',
 'beauflynn',
 'beautiful',
 'beauty',
 'beckysullivan',
 'becominganadult',
 'bed',
 'befriends',
 'began',
 'begin',
 'beginning',
 'begins',
 'behavior',
 'believe',
 'believed',
 'believes',
 'bell',
 'beloved',
 'ben',
 'benaffleck',
 'benavente',
 'benedictcumberbatch',
 'benfoster',
 'bengarant',
 'beniciodeltoro',
 'benjaminbratt',
 'benjamÃ­nfernÃ¡ndez',
 'benkingsley',
 'bennett',
 'bennettwalsh',
 'benstiller',
 'bent',
 'bentley',
 'benwaisbren',
 'berger',
 'berlin',
 'berndeichinger',
 'berniemac',
 'besser',
 'best',
 'bestfriend',
 'bet',
 'bethgrant',
 'betrayal',
 'bettemidler',
 'better',
 'bible',
 'big',
 'biggest',
 'biker',
 'billabbott',
 'billbernstein',
 'billcarraro',
 'billcobbs',
 'billcorso',
 'billhader',
 'billionaire',
 'billjohnson',
 'billmurray',
 'billnighy',
 'billnunn',
 'billo',
 'billpankow',
 'billpaxton',
 'billpope',
 'billpullman',
 'billy',
 'billybobthornton',
 'billyconnolly',
 'billycrudup',
 'billycrystal',
 'billyhopkins',
 'billyweber',
 'billyzane',
 'biography',
 'bird',
 'birth',
 'birthday',
 'bishop',
 'bissell',
 'bit',
 'bite',
 'bizarre',
 'black',
 'blackmail',
 'blackpeople',
 'blade',
 'blake',
 'blind',
 'bliss',
 'block',
 'blonde',
 'blood',
 'bloody',
 'bloom',
 'blow',
 'blue',
 'board',
 'boat',
 'bob',
 'bobbadami',
 'bobbalaban',
 'bobbeemer',
 'bobby',
 'bobbycannavale',
 'bobbyfarrelly',
 'bobgunton',
 'bobhoskins',
 'bobkensinger',
 'bobweinstein',
 'bobyari',
 'body',
 'bodyguard',
 'bokeemwoodbine',
 'bomb',
 'bombing',
 'bond',
 'bonniehunt',
 'bonnietimmermann',
 'book',
 'books',
 'border',
 'bored',
 'born',
 'boss',
 'boston',
 'bound',
 'bounty',
 'bountyhunter',
 'bourne',
 'box',
 'boxer',
 'boxing',
 'boy',
 'boyd',
 'boyfriend',
 'boyle',
 'boys',
 'bradbird',
 'braddourif',
 'bradgarrett',
 'bradleycooper',
 'bradpitt',
 'bradsherman',
 'brain',
 'brandontrost',
 'brave',
 'bravery',
 'break',
 'breaking',
 'breaks',
 'breckinmeyer',
 'brendanfraser',
 'brendangleeson',
 'brentspiner',
 'brettratner',
 'brian',
 'brianavery',
 'briancox',
 'briandennehy',
 'briandepalma',
 'briandoyle',
 'briangrazer',
 'brianhelgeland',
 'brianheller',
 'brianj',
 'briann',
 'brianrichards',
 'briantaylor',
 'briantyler',
 'bride',
 'bridge',
 'brielarson',
 'brien',
 'brilliant',
 'bring',
 'bringing',
 'brings',
 'brink',
 'britain',
 'british',
 'britishsecretservice',
 'brittanymurphy',
 'broadway',
 'broccoli',
 'broderickjohnson',
 'broke',
 'broken',
 'brooklyn',
 'brooks',
 'brother',
 'brotherbrotherrelationship',
 'brothers',
 'brothersisterrelationship',
 'brought',
 'brown',
 'brubaker',
 'bruce',
 'brucea',
 'bruceberman',
 'brucecampbell',
 'brucedern',
 'brucefowler',
 'brucegreen',
 'brucegreenwood',
 'brucemcgill',
 'brucespence',
 'brucewillis',
 'brutal',
 'brutality',
 'brutally',
 'bryan',
 'bryanbowen',
 'bryancranston',
 'bryansinger',
 'bubasman',
 'buck',
 'buckley',
 'buddy',
 'build',
 'building',
 'bully',
 'bumbling',
 'buried',
 'burke',
 'burns',
 'burton',
 'burtreynolds',
 'bus',
 'bush',
 'business',
 'businessman',
 'butler',
 'buy',
 'byrne',
 'cabin',
 'cabrera',
 'cal',
 'calebdeschanel',
 'california',
 'called',
 'calls',
 'callumkeithrennie',
 'calvin',
 'came',
 'camera',
 'cameron',
 'cameroncrowe',
 'camerondiaz',
 'camillefriend',
 'camp',
 'campaign',
 'campanelli',
 'campbell',
 'campus',
 'canada',
 'canadian',
 'cancer',
 'capable',
 'capitalism',
 'captain',
 'captive',
 'capture',
 'captured',
 'car',
 'caracciolojr',
 'carchase',
 'carcrash',
 'card',
 'care',
 'career',
 'caribbean',
 'carl',
 'carlagugino',
 'carlson',
 'carmen',
 'carola',
 'carolineaaron',
 'carolinegoodall',
 'carolkiefer',
 'carolspier',
 'carpenter',
 'carrace',
 'carrie',
 'carriefisher',
 'carry',
 'carrying',
 'carter',
 'carterburwell',
 'caruso',
 'cary',
 'caryelwes',
 'case',
 'caseyaffleck',
 'cash',
 'casino',
 'cast',
 'castle',
 'cat',
 'catch',
 'catches',
 'cateblanchett',
 'catehardman',
 'catherinehardwicke',
 'catherineharper',
 'catherinekeener',
 'catherineo',
 'catherinezeta',
 'cathey',
 'catholic',
 'cathysandrich',
 'caught',
 'cause',
 'caused',
 'causes',
 'causing',
 'cave',
 'cedrictheentertainer',
 'celebrate',
 'celebration',
 'celebrity',
 'celiad',
 'celiaimrie',
 'celiaweston',
 'center',
 'centered',
 'central',
 'centuries',
 'century',
 'certain',
 'chadoman',
 'chain',
 'challenge',
 'challenged',
 'challenges',
 'champion',
 'championship',
 'chance',
 'chancekelly',
 'change',
 'changed',
 'changes',
 'changing',
 'channingtatum',
 'chaos',
 'character',
 'characters',
 'charge',
 'charged',
 'charles',
 'charlesdance',
 'charlesdurning',
 'charlesmaynes',
 'charlesroven',
 'charless',
 'charlesw',
 'charlie',
 'charliekaufman',
 'charliesheen',
 'charlizetheron',
 'charlotterampling',
 'charltonheston',
 'charming',
 'chase',
 'chavez',
 'chazzpalminteri',
 'cheating',
 'cheechmarin',
 'chef',
 'chevychase',
 'chicago',
 'chief',
 'child',
 'childabuse',
 'childhood',
 'children',
 'chilling',
 'chimcbride',
 'china',
 'chinese',
 'chip',
 'chiwetelejiofor',
 'chloÃ«gracemoretz',
 'choice',
 'choose',
 'chosen',
 'chris',
 'chrisanderson',
 'chrisbender',
 'chrisbrown',
 'chrisburdon',
 'chriscolumbus',
 'chriscooper',
 'chriscornwell',
 'chrisellis',
 'chrisevans',
 'chrishaarhoff',
 'chrishemsworth',
 'chrishogan',
 'chrisjenkins',
 'chrisl',
 'chrislebenzon',
 'chrismiller',
 'chriso',
 'chrispine',
 'chrispratt',
 'chrisrock',
 'chrissanders',
 'chrissnyder',
 'christ',
 'christensen',
 'christian',
 'christianbale',
 'christianity',
 'christianp',
 'christianslater',
 'christianwagner',
 'christinaapplegate',
 'christinaricci',
 'christinebaranski',
 'christinewilson',
 'christmas',
 'christmasparty',
 'christophebeck',
 'christopher',
 'christopherassells',
 'christopherboyes',
 'christopherguest',
 'christopherlee',
 'christopherlennertz',
 'christopherlloyd',
 'christophermcdonald',
 'christophermcquarrie',
 'christophermiller',
 'christophermintz',
 'christophernolan',
 'christopherplummer',
 'christophers',
 'christopherscarabosio',
 'christophert',
 'christopherwalken',
 'christopheryoung',
 'christophwaltz',
 'chrisweitz',
 'chronicles',
 'chu',
 'chuckduke',
 'chuckmichael',
 'church',
 'cia',
 'ciarÃ¡nhinds',
 'cillianmurphy',
 'cindycarr',
 'circle',
 'circumstances',
 'circus',
 'citizens',
 'city',
 'civil',
 'civilwar',
 'claim',
 'claims',
 'clair',
 'claire',
 'claireforlani',
 'clan',
 'clancybrown',
 'clark',
 'clarkgregg',
 'clash',
 'class',
 'classic',
 'classmate',
 'claudevandamme',
 'claytontownsend',
 'cleaduvall',
 'clean',
 'clear',
 'clerk',
 'client',
 'cliffcurtis',
 'cliffmartinez',
 'cliftoncollinsjr',
 'climbing',
 'clinteastwood',
 'clinthoward',
 'clintmansell',
 'clinton',
 'cliveowen',
 'clock',
 'clone',
 'clorisleachman',
 'close',
 'closer',
 'club',
 'clues',
 'coach',
 'coast',
 'cocaine',
 'code',
 'codycameron',
 'coe',
 'cohen',
 'cold',
 'coldwar',
 'cole',
 'colehauser',
 'colinanderson',
 'colinfarrell',
 'colinfirth',
 'colinsalmon',
 'colinwilson',
 'collapse',
 'colleague',
 'colleagues',
 'collect',
 'collection',
 'colleenatwood',
 'colleencamp',
 'college',
 'collide',
 'collins',
 'colmfeore',
 'colonel',
 'colorful',
 'coma',
 'combat',
 'come',
 'comedian',
 'comedy',
 'comes',
 'comic',
 'coming',
 'comingofage',
 'commander',
 'commit',
 'commitment',
 'committed',
 'common',
 'community',
 'company',
 'compete',
 'competition',
 'complete',
 'completely',
 'complex',
 'complicated',
 'complications',
 'computer',
 'concert',
 'condition',
 'confidence',
 'conflict',
 'confront',
 'connected',
 'connection',
 'connell',
 'connor',
 'conradbuffiv',
 'conradvernon',
 'consequences',
 'conspiracy',
 'contact',
 'contest',
 'continue',
 'continues',
 'contract',
 'control',
 'controversial',
 'convict',
 'convicted',
 'convince',
 'convinced',
 'convinces',
 'cook',
 'cool',
 'cooper',
 'cop',
 'cope',
 'cops',
 'coreenmayrs',
 'coreyburton',
 'corporate',
 'corporation',
 'corpse',
 'corrupt',
 'corruption',
 'cosmaspaulbolgerjr',
 'cost',
 'costanzo',
 'costas',
 'count',
 'country',
 'countryside',
 'couple',
 'couples',
 'courage',
 'course',
 'court',
 'courtcase',
 'cousin',
 'cover',
 'covert',
 'cowardliness',
 'cowboy',
 'crack',
 'craig',
 'craigalpert',
 'craigarmstrong',
 'craigbarron',
 'craigberkey',
 'craighenighan',
 'craigr',
 'craigrobinson',
 'craigt',
 'crash',
 'crazy',
 'create',
 ...]

In [104]:
from sklearn.metrics.pairwise import cosine_similarity

In [105]:
similarity = cosine_similarity(vectors)

In [106]:
sorted(list(enumerate(similarity[0])),reverse=True,key=lambda x:x[1])[1:6]

[(25, 0.27887305899520104),
 (2409, 0.2673935429164744),
 (282, 0.24174688920761414),
 (279, 0.2330745053742094),
 (3443, 0.18802535827258876)]

In [107]:
def recommend1(actor):
  movie_index = new_df[new_df['cast'] == actor].index[0]
  distances = similarity[movie_index]
  movies_list = sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:6]
  for i in movies_list:
    print(i)

In [108]:
def recommend(movie):
  movie_index = new_df[new_df['title'] == movie].index[0]
  distances = similarity[movie_index]
  movies_list = sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:6]
  for i in movies_list:
    print(i)

In [109]:
recommend('Batman Begins')

(65, 0.45385138564989774)
(3, 0.3664385790890539)
(9, 0.26399142041825235)
(1363, 0.25734954899265206)
(4641, 0.24759378423606918)

In [110]:
import pickle

In [111]:
pickle.dump(new_df,open('movies.pkl','wb'))

In [112]:
new_df['title'].values

array(['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre',
       ..., 'Signed, Sealed, Delivered', 'Shanghai Calling',
       'My Date with Drew'], dtype=object)

In [113]:
pickle.dump(new_df,open('movies.pkl','wb'))

In [114]:
new_df['title'].values

array(['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre',
       ..., 'Signed, Sealed, Delivered', 'Shanghai Calling',
       'My Date with Drew'], dtype=object)

In [115]:
pickle.dump(new_df.to_dict(),open('movie_dict.pkl','wb'))

In [57]:
pickle.dump(similarity,open('similarity.pkl','wb'))